[workspace]
members = ["crates/burnout-core", "crates/burnout-layout", "crates/burnout-iso", "crates/burnout"]
resolver = "2"

[workspace.package]
version = "0.0.0"
edition = "2021"
rust-version = "1.77"
license = "MIT"
repository = "https://github.com/Stiven-Gjekaj/burnout"
authors = ["Stiven Gjekaj <stivenagostingjekaj@gmail.com>"]

[profile.release]
strip = true
lto = true
codegen-units = 1
